---
dsn: mysql://schemaxuser:123456@127.0.0.1:13306/schemax?loc=Local&parseTime=true&charset=utf8mb4
table_sets:
  - set_name: default
    tables:
      - a_index
      - a_index_composite
      - a_manual_table
      - a_primary
      - a_primary_composite
      - a_primary_multi
  - set_name: a_bit_of_everything
    tables:
      - a_bit_of_everything

plugins:
  - plugin: schemax-gen-debug
    out: to/{set_name}
    opts:
      - package=model
  # - plugin: json
  #   out: /path/to/{set_name}/{table_name}.json
  # - plugin: yaml
  #   out: /path/to/{set_name}/{table_name}.yaml
