version: "3.1"
services:
  mysqldb:
    networks:
      - schemax
    image: mysql:8.4
    environment:
      MYSQL_USER: schemaxuser
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: schemax
      TZ: Asia/Shanghai
    ports:
      - "13306:3306"
  postgresdb:
    networks:
      - schemax
    image: postgres:15
    environment:
      POSTGRES_USER: schemaxuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: schemax
      TZ: Asia/Shanghai
    ports:
      - "15432:5432"
networks:
  schemax: {}
